### PR TITLE
Adding FSharpLint.Build

### PR DESCRIPTION
**Pull request by HenrikRxn**
**Work in progress** part of #4 

Added FSharpLint.Build v0.4.4 to Domain project

Having some issue with FSharpLint.Build on my machine so want to how it behaves on Appveyor

### CODE REVIEW

**Comment by parthopdas** [comment]
Not merging this one due to the invalid tag as I am not sure what it means. Pls let me know @HenrikRxn

**Comment by HenrikRxn** [comment]
As the initial PR statement says this is work in progress to see how it behaves on the build server. 

Furthermore the fact that I haven't assigned a reviewer should strongly indicate that it should not be considered for merging.

I would suggest adding a WIP tag to the project that can be used to signify that a PR is still being worked on and is not ready for merging yet. There are a number of reasons why this could be useful, e.g. to share an early design to get feedback.

**Comment by HenrikRxn** [comment]
Closing for now as I have opened issue at FSharpLint repository

**Comment by parthopdas** [comment]
Understood, we can adopt that convention. Thanks Henrik.

**Comment by HenrikRxn** [comment]
Hi Partho

Reading my own comment in your reply made me realise it sounded a bit harsh
and it was not my intention. Hope you took no offence

Regards, Henrik

**Comment by parthopdas** [comment]
None taken, don't worry about it. :) I'll add the WIP tag shortly.

**Pull request closed without merging**
